/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fundamental/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Fundamental Ratio */
        get: operations["read_fundamental_ratio_api_fundamental__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /**
         * FundamentalMetrics
         * @example {
         *       "companyName": "Apple Inc.",
         *       "metrics": [
         *         {
         *           "currentRatio": 1.07,
         *           "debtAssetRatio": 0.82,
         *           "operatingCashFlowPerShare": 5.67,
         *           "quickRatio": 0.88,
         *           "totalAssets": 351,
         *           "totalLiabilities": 287.91,
         *           "year": 2023
         *         }
         *       ],
         *       "ticker": "AAPL"
         *     }
         */
        FundamentalMetrics: {
            /**
             * Ticker
             * @description Stock ticker symbol
             */
            ticker: string;
            /**
             * Companyname
             * @description Name of the company
             */
            companyName: string;
            /**
             * Metrics
             * @description List of financial metrics for each year
             */
            metrics: components["schemas"]["YearMetrics"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** YearMetrics */
        YearMetrics: {
            /**
             * Year
             * @description Year of the financial metrics
             */
            year: number;
            /**
             * Roe
             * @description Return on equity for the year
             * @default 0
             */
            ROE: number;
            /**
             * Debtassetratio
             * @description Debt to asset ratio for the year
             * @default 0
             */
            debtAssetRatio: number;
            /**
             * Currentratio
             * @description Current ratio for the year
             * @default 0
             */
            currentRatio: number;
            /**
             * Quickratio
             * @description Quick ratio for the year
             * @default 0
             */
            quickRatio: number;
            /**
             * Operatingcashflowpershare
             * @description Operating cash flow per share for the year
             * @default 0
             */
            operatingCashFlowPerShare: number;
            /**
             * Liabilitiesassetratio
             * @description Liabilities to asset ratio for the year
             * @default 0
             */
            liabilitiesAssetRatio: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_fundamental_ratio_api_fundamental__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundamentalMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
