ROW_ALIASES = {
    "shares_outstanding": [
        "ordinary shares number",
        "basic shares outstanding",
        "common stock",
    ],
    "stockholders_equity": ["Stockholders Equity"],
    "net_income": ["net income from continuing operations", "net income"],
    "current_assets": ["current assets", "total current assets"],
    "current_liabilities": ["current liabilities", "total current liabilities"],
    "inventory": ["inventory", "inventories"],
    "total_liabilities": [
        "total liabilities net minority interest",
        "total liabilities",
    ],
    "total_debt": ["total debt", "interest bearing debt"],
    "total_assets": ["total assets"],
    # cash_flow
    "net_income": ["net income"],
    "operating cash flow": ["operating cash flow"],
}

ROW_ALIASES_CN = {
    "基本每股收益(元)":"eps",
    "每股经营现金流(元)":"operatingCashFlowPerShare",
    "销售毛利率":'grossProfit',
    "净资产收益率":"roe",
    "流动比率":'currentRatio',
    "资产负债率":'liabilitiesAssetRatio',

    "科目\时间":"subject/time",
    # Profitability Metrics
    "净利润同比增长率":"Year-over-Year Net Profit Growth Rate",
    "扣非净利润(元)": "Non-GAAP Net Profit",
    "扣非净利润同比增长率":"YoY Non-GAAP Net Profit Growth Rate",
    "营业总收入(元)":"Total Operating Revenue",
    "营业总收入同比增长率":"YoY Operating Revenue Growth Rate",
    "净利润(元)": 'net_income',
    "销售净利率":"Net Profit Margin",
    # Capital Structure Metrics
    "每股净资产(元)": "Net Assets Per Share",
    "每股资本公积金(元)": "Capital Reserve Per Share",
    "每股未分配利润(元)": " Retained Earnings Per Share",
    "净资产收益率-摊薄": "Diluted Return on Equity",
    "产权比率": "Equity Ratio",
    # Operating Efficiency Metrics
    "营业周期(天)": "Operating Cycle",
    "存货周转率(次)": "Inventory Turnover Ratio",
    "存货周转天数(天)": "Days Sales of Inventory",
    "应收账款周转天数(天)": "Days Sales Outstanding",
    # Liquidity Metrics
    "速动比率": "Quick Ratio",
    "保守速动比率":"Conservative Quick Ratio"
}

CAC40 = [
    "AC.PA",
    "AI.PA",
    "AIR.PA",
    "MT.AS",
    "ATO.PA",
    "CS.PA",
    "BNP.PA",
    "EN.PA",
    "CAP.PA",
    "CA.PA",
    "ACA.PA",
    "BN.PA",
    "DSY.PA",
    "ENGI.PA",
    "EL.PA",
    "RMS.PA",
    "KER.PA",
    "OR.PA",
    "LR.PA",
    "MC.PA",
    "ML.PA",
    "ORA.PA",
    "RI.PA",
    "PUB.PA",
    "RNO.PA",
    "SAF.PA",
    "SGO.PA",
    "SAN.PA",
    "SU.PA",
    "GLE.PA",
    "STM.PA",
    "FTI.PA",
    "FP.PA",
    "URW.PA",
    "VIE.PA",
    "DG.PA",
    "VIV.PA",
]
