ROW_ALIASES = {
    "shares_outstanding": [
        "ordinary shares number",
        "basic shares outstanding",
        "common stock",
    ],
    "stockholders_equity": ["Stockholders Equity"],
    "net_income": ["net income from continuing operations", "net income"],
    "current_assets": ["current assets", "total current assets"],
    "current_liabilities": ["current liabilities", "total current liabilities"],
    "inventory": ["inventory", "inventories"],
    "total_liabilities": [
        "total liabilities net minority interest",
        "total liabilities",
    ],
    "total_debt": ["total debt", "interest bearing debt"],
    "total_assets": ["total assets"],
    # cash_flow
    "net_income": ["net income"],
    "operating cash flow": ["operating cash flow"],
}

ROW_ALIASES_CN = {
    "净利润": 'net_income',
    "每股经营现金流":"operatingCashFlowPerShare",
    "销售毛利率":'grossProfit',
    "净资产收益率":"roe",
    "流动比率":'currentRatio',
    "资产负债率":'liabilitiesAssetRatio'
}

CAC40 = [
    "AC.PA",
    "AI.PA",
    "AIR.PA",
    "MT.AS",
    "ATO.PA",
    "CS.PA",
    "BNP.PA",
    "EN.PA",
    "CAP.PA",
    "CA.PA",
    "ACA.PA",
    "BN.PA",
    "DSY.PA",
    "ENGI.PA",
    "EL.PA",
    "RMS.PA",
    "KER.PA",
    "OR.PA",
    "LR.PA",
    "MC.PA",
    "ML.PA",
    "ORA.PA",
    "RI.PA",
    "PUB.PA",
    "RNO.PA",
    "SAF.PA",
    "SGO.PA",
    "SAN.PA",
    "SU.PA",
    "GLE.PA",
    "STM.PA",
    "FTI.PA",
    "FP.PA",
    "URW.PA",
    "VIE.PA",
    "DG.PA",
    "VIV.PA",
]
